import '../models/audio_lesson.dart';

final List<AudioLesson> mockAudioLessons = [
  AudioLesson(
    id: '1',
    title: "Сэтгэлийн хүчээ мэдэр",
    lessonName: 'Бясалгал 1',
    lessonNumber: "Хичээл 1",
    startTime: "06:00",
    duration: Duration(minutes: 10),
    audioPath: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    lessonDescription:
        '12-р сарын 6-ны өглөө 04 цагт хийнэ, орой 18 цагаас давтаж хийнэ.',
    image: 'assets/images/bg/setgelsmall.png',
    bgImage: 'assets/images/bg/setgelbg.png',
    remainingDays: '5',
    price: 289000,
    category: "Эрүүл мэнд",
    rate: 4.5,
  ),
  AudioLesson(
    id: '2',
    title: "Эдгэрэлийн дасгалжуулалт",
    lessonName: 'Бясалгал 2',
    lessonNumber: "Хичээл 2",
    startTime: "07:00",
    duration: Duration(minutes: 12),
    audioPath: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    lessonDescription:
        '12-р сарын 8-ны өглөө 04 цагт хийнэ, орой 20 цагаас давтаж хийнэ.',
    image: 'assets/images/bg/edgerelsmall.png',
    bgImage: 'assets/images/bg/edgerelbg.png',
    remainingDays: '10',
    price: 258300,
    category: "Эрүүл мэнд",
    rate: 5,
  ),
  AudioLesson(
    id: '3',
    title: "Хариу Мэдүүлэг",
    lessonName: 'Бясалгал 3',
    lessonNumber: "Хичээл 3",
    startTime: "08:00",
    duration: Duration(minutes: 8),
    audioPath: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    lessonDescription:
        '12-р сарын 10-ны өглөө 05 цагт, орой 19 цагаас давтан хийнэ.',
    image: 'assets/images/bg/hariusmall.png',
    bgImage: 'assets/images/bg/setgelbg.png',
    remainingDays: '7',
    price: 199000,
    category: "Нэмэлт сургалт",
    rate: 4,
  ),
  AudioLesson(
    id: '4',
    title: "Хүсэл бүтээх хүч",
    lessonName: 'Бясалгал 4',
    lessonNumber: "Хичээл 4",
    startTime: "09:00",
    duration: Duration(minutes: 15),
    audioPath: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    lessonDescription:
        '12-р сарын 12-ны өглөө 06 цагт, орой 21 цагаас давтан хийнэ.',
    image: 'assets/images/bg/huselsmall.png',
    bgImage: 'assets/images/bg/setgelbg.png',
    remainingDays: '12',
    price: 0,
    category: "Үнэгүй сургалт",
    rate: 3.5,
  ),
  AudioLesson(
    id: '5',
    title: "Мөнгөний мантра",
    lessonName: 'Бясалгал 5',
    lessonNumber: "Хичээл 5",
    startTime: "10:00",
    duration: Duration(minutes: 20),
    audioPath: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    lessonDescription:
        '12-р сарын 15-ны өглөө 07 цагт, орой 20 цагаас давтан хийнэ.',
    image: 'assets/images/bg/mongosmall.png',
    bgImage: 'assets/images/bg/setgelbg.png',
    remainingDays: '15',
    price: 150000,
    category: "Хөнгөлөлттэй сургалт",
    rate: 3,
  ),
];
